apiVersion: v1
kind: Namespace
metadata:
  name: o11y-k8s-talk

--- 
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: o11y-k8s-talk
  labels:
    app: postgres-database
    component: database
    owner: disbursement-team
    business_unit: disbursement
type: Opaque
stringData:
  POSTGRES_DB: disbursement_demo
  POSTGRES_USER: demo
  POSTGRES_PASSWORD: a_super_secure_password

--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: postgres-database
    component: database
    owner: disbursement-team
    business_unit: disbursement
spec:
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/postgres
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: o11y-k8s-talk
  labels:
    app: postgres-database
    component: database
    owner: disbursement-team
    business_unit: disbursement
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres-pv

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: o11y-k8s-talk
  labels:
    app: postgres-database
    component: database
    owner: disbursement-team
    business_unit: disbursement
data:
  postgresql.conf: |
    log_statement = 'all'
    log_duration = on
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%,app=%a,client=%h '
    shared_buffers = 128MB
    max_connections = 100
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-database
  namespace: o11y-k8s-talk
  labels:
    app: postgres-database
    component: database
    owner: disbursement-team
    business_unit: disbursement
spec:
  selector:
    matchLabels:
      app: postgres-database
  template:
    metadata:
      labels:
        app: postgres-database
    spec:
      containers:
      - name: postgres-database
        image: postgres:16-alpine
        securityContext:
          runAsUser: 999 # postgres
          runAsGroup: 999
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        envFrom:
          - secretRef:
              name: postgres-secret
        volumeMounts:
          - name: pgdata
            mountPath: /var/lib/postgresql/data
            subPath: pgdata # avoiding directory not empty error
        readinessProbe:
          exec:
            command:
              - "/bin/sh -c pg_isready -U demo -d disbursement_demo"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
              - "/bin/sh -c pg_isready -U demo -d disbursement_demo"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 5432
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter:latest
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_DB
          - name: DATA_SOURCE_NAME
            value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@localhost:5432/$(POSTGRES_DB)?sslmode=disable"
        ports:
          - containerPort: 9187
            name: metrics
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc


---
apiVersion: v1 
kind: Service
metadata:
  name: postgres
  namespace: o11y-k8s-talk
  labels:
    app: postgres-database
    component: database
    owner: disbursement-team
    business_unit: disbursement
spec:
  selector:
    app: postgres-database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
