apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: o11y-k8s-talk
  labels:
    app: otel-collector
    component: alias
    part-of: o11y-k8s-talk
spec:
  type: ExternalName
  externalName: alloy.monitoring.svc.cluster.local
